#!/bin/bash

echo "Updating and upgrading apt packages"
sudo apt update -y;sudo apt upgrade -y

echo "Setup firewall"
sudo apt install ufw
sudo ufw allow OpenSSH
sudo ufw allow http
sudo ufw allow https
sudo ufw allow 4000/tcp
sudo ufw enable

echo "Downloading nodejs"
curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -

echo "Install nodejs"
sudo apt-get install -y nodejs

echo "Checking node and npm versions"
node -v
npm -v

echo "Install snapd and core"
sudo apt install snapd
sudo snap install core

echo "Install certbot"
sudo snap install --classic -y certbot

echo "Create symbolic link for certbot from snap bin to usr bin"
sudo ln -s /snap/bin/certbot /usr/bin/certbot

echo "Create diffie hellman key"
sudo openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048

echo "Create config file for SSL"
touch /etc/nginx/snippets/ssl-params.conf

echo "Write to the file"
cat >> /etc/nginx/snippets/ssl-params.conf << EOL
# See https://cipherli.st/ for details on this configuration
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_prefer_server_ciphers on;
ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0
ssl_session_cache shared:SSL:10m;
ssl_session_tickets off; # Requires nginx >= 1.5.9
ssl_stapling on; # Requires nginx >= 1.3.7
ssl_stapling_verify on; # Requires nginx => 1.3.7
resolver 8.8.8.8 8.8.4.4 valid=300s;
resolver_timeout 5s;
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
add_header X-Frame-Options DENY;
add_header X-Content-Type-Options nosniff;
# Add our strong Diffie-Hellman group
ssl_dhparam /etc/ssl/certs/dhparam.pem;
EOL
